version: "3.3"
services:
  db:
    image: mysql/mysql-server:5.7
    container_name: dev-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
  dynamo:
    image: "amazon/dynamodb-local"
    container_name: dev-dynamodb
    volumes:
      - dynamodb_local_db:/dynamodb_local_db
    ports:
      - "8000:8000"
# Names our volume
volumes:
  mysql-db:
  dynamodb_local_db: